server:
  port: 8761

spring:
  application:
    name: service-registry
  cloud:
    config:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info