version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: teamconnect-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: teamconnect
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - teamconnect-network

  # Service Registry
  service-registry:
    build:
      context: ./service-registry
    container_name: teamconnect-service-registry
    ports:
      - "8761:8761"
    networks:
      - teamconnect-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: teamconnect-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    networks:
      - teamconnect-network

networks:
  teamconnect-network:
    driver: bridge

volumes:
  postgres-data: